### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by orchid00** [useR-2018/cooee#6]
Should we add requirements?

required_packages <- c("shinydashboard", "googlesheets", "DT")

**Comment by mitchelloharawild** [comment]
For easy installation of missing packages? Such as:
```{r}
install.packages(required_packages)
```

**Comment by orchid00** [comment]
Yes just to save time when installing. there might be other packages required that I coincidentally had, but it took a few tries with one message after the other to install to run the app.

**Comment by mitchelloharawild** [comment]
Added in  5a9311d
