### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by orchid00** [useR-2018/cooee#7]
Is there a way to switch from abstracts to scholarhsips with a dropdown or something? 
By now I had to clone the repo with another name.

**Comment by dicook** [comment]
They are separate apps.

So, yes, you need to clone twice to get both apps. 

> On Mar 3, 2018, at 10:05 PM, Paula Andrea <notifications@github.com> wrote:
> 
> Is there a way to switch from abstracts to scholarhsips with a dropdown or something?
> By now I had to clone the repo with another name.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

~*~*~*~
Professor Dianne Cook
Department of Econometrics and Business Statistics
E762A Menzies Building 
20 Chancellors Walk
Monash University
Clayton, VIC 3800
+61 (0)3 990 52608 (office)
+61 (0)4 312 71613 (mobile)
dicook@monash.edu
http://dicook.github.io
@visnut
